---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-mcp-secret
    template:
      data:
        UNIFI_USERNAME: "{{ .UNIFI_USERNAME }}"
        UNIFI_PASSWORD: "{{ .UNIFI_PASSWORD }}"
  dataFrom:
    - extract:
        key: unifi-mcp
