---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - icon: github
          href: https://github.com/

- Social:
    - Reddit:
        - icon: reddit
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/

- Gaming:
    - BeforeIPlay:
        - icon: https://beforeiplay.com/images/beforeiplaylogo.png
          href: https://beforeiplay.com/
