---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Utilities:
    - OctoPi:
        icon: octoprint
        description: 3D printer web interface
        href: https://octopi
        ping: localhost
    - Proxmox:
        icon: proxmox
        description: Virtualization platform
        href: https://cupcakes.dog-hen.ts.net:8006
        ping: localhost
