apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9CDEfVZ6uIjoIehZqHdlYw7AkcU=,iv:HC5Z8wutqhbUvwk6dAB/GsovRE5+xpS6z6/B7v/sVA0=,tag:fKtgx50/4CyvFdpTEbEtEw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:MPn8DKoaBLCM68czVMhVb15lH84E07KQUt8fTxnFzlmGoOY3Cw==,iv:MDqyh+gZAdCG81L2CHQoXOQaxiREiAQg0V3phAplmH4=,tag:b07X/5bcIcAKhe+UgxFcEg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YUEDhGySJ1AZr7YZTvGHryhz8Q==,iv:WnQuwGpN5538SsPwc1wjcxMr/1ZG7SZiylXANt55KUc=,tag:NBmMm9SZ7GjAqeVd5OEvKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19g8y23904c6pcwuqpldhke2vdrfwlyq3vh685llzf2xg8ntd3u6su59vxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ0o1K1dldkRUODlUQ0JI
            M29LOTA5clZJYzJzS3ZBZEFzQy9DNW16VVFzCllKY2c2T1d4VytWMFI1NzVtTW9M
            WXZUSndqZ21XNEgyWi9KdTFjN01mdGsKLS0tIC9ESDZQS1V1VmFrR1ZRTmxUczRY
            MWdxQWV0alNLanJTeFFRUEpiTUwxcEkKuhE6uzsW1xYJmo+/zktO/6KLP1vDi6Xs
            YGzLjpQXHuHmUDVhvZbHxMEKqe8mtwoe5vyUf1/zxWcSiRB3ejZ/4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:32:49Z"
    mac: ENC[AES256_GCM,data:LkvkOscmUHYDYuDemNdlnglWTadklto6WJA2/ZoTkUFtfEqCq2lnexGy+8QvyETkRa7zWJbLFClW65lhHmsd6IxXDoyqKv98BUUl1xEU8n9uibidFr7+EggnRstW0Ym09IpjmW3hIeJ9Lk31OnZOOTDnukfvasnWoD/Dn26lVc4=,iv:E/VdJ21bAWaV9u8IUrVAtrM+SxjKR7eCWIkuje3cvsA=,tag:ES4Elq4pSawU5y9O+rAbdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
