---
- name: Add Hashicorp apt repository key.
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: '0644'
    force: true

- name: Add Hashicorp apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: "hashicorp"
    state: present
    update_cache: true

- name: Install consul
  ansible.builtin.apt:
    pkg:
      - consul

- name: Copy agent cert
  ansible.builtin.copy:
    src: consul-agent-ca.pem
    dest: /etc/consul.d/
    owner: consul
    group: consul
    mode: 0600
  notify: Restart consul

- name: Copy server certs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/consul.d/
    owner: consul
    group: consul
    mode: 0600
  loop:
    - homelab-server-consul-0.pem
    - homelab-server-consul-0-key.pem
  when: "'consul_server' in group_names"
  notify: Restart consul

- name: Ensure agents do not have certs
  ansible.builtin.file:
    path: "/etc/consul.d/{{ item }}"
    state: absent
  loop:
    - homelab-server-consul-0.pem
    - homelab-server-consul-0-key.pem
  when: "'consul_agents' in group_names"

- name: Copy consul base config file
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640
  notify: Restart consul

- name: Ensure proper permissions
  ansible.builtin.file:
    path: /etc/consul.d
    owner: consul
    group: consul
    recurse: true
  notify: Restart consul

- name: Enable consul
  ansible.builtin.service:
    name: consul
    enabled: true
    state: started
