#cloud-config

ssh_pwauth: false

timezone: Etc/UTC

package_update: true
package_upgrade: true
package_reboot_if_required: true

apt:
  sources:
    pkgs_tailscale_com_stable_ubuntu.list:
      source: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
      keyid: 2596A99EAAB33821893C0A79458CA832957F5868
packages:
  - tailscale
runcmd:
  - [tailscale, up, --ssh, --authkey, tskey-auth]

users:
- name: caycehouse
  passwd: $6$zpn8R2g0kxjloJ3J$UpMKBvc/IV.FC76GEEyK9a.tgzjSFJ5ZE.yC7Wxz/.ap07j29Oxm0.gV4kUV6ChcQJD5xUIFgsgo1DXIXC0ho0
  shell: /bin/bash
  ssh_import_id: gh:caycehouse
  sudo: ALL=(ALL) NOPASSWD:ALL
