# Example usage: ansible-playbook state.yml
# This playbook deploys my whole homelab.

---

- name: Play for all machines
  hosts: all
  vars:
    tailscale_args: "--ssh"
  roles:
    - {role: common, tags: common}
    - {role: artis3n.tailscale, tags: tailscale}
  vars_files: vault.yml

- name: Play to add swap to needed machines
  hosts: all,!proxmox_servers,!klipper
  vars:
    swap_file_size_mb: '8192'
  roles:
    - {role: geerlingguy.swap, tags: swap}

- name: Play for proxmox machines
  hosts: cupcakes
  roles:
    - {role: proxmox, tags: proxmox}

- name: Play for docker nodes
  hosts: docker_nodes
  vars:
    docker_daemon_options:
      mtu: 1280
  vars_files: vault.yml
  roles:
    - {role: geerlingguy.docker, tags: docker}
    - {role: portainer, tags: portainer}
