---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  # Binaries
  PYTHON_BIN: python3

tasks:
  default: task -l

includes:
  ansible: .taskfiles/Ansible.yml
  workstation: .taskfiles/Workstation.yml
