---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-vanillatweaks
data:
  vt-datapacks.json: |
    {
      "type": "datapacks",
      "version": "${MC_VERSION}",
      "packs": {
        "informative": [
          "nether portal coords",
          "afk display",
          "coordinates hud",
          "durability ping",
          "track raw statistics",
          "track statistics"
        ],
        "decorative-cosmetic": [
          "wandering trades hermit edition",
          "player head drops",
          "silence mobs",
          "more mob heads",
          "armor statues"
        ],
        "convenience": [
          "multiplayer sleep"
        ],
        "gameplay-changes": [
          "anti enderman grief"
        ]
      }
    }
  vt-craftingtweaks.json: |
    {
      "type": "craftingtweaks",
      "version": "${MC_VERSION}",
      "packs": {
        "quality-of-life": [
          "universal dyeing"
        ]
      }
    }
