---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    fullnameOverride: *app
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.1.0-java25-graalvm@sha256:57390cb09b3450551bed092d4e60328e991ca556ad28296efb944aa010460ec0
      pullPolicy: IfNotPresent
    startupProbe:
      enabled: true
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: &hostname mc.thefryer.games
      external-dns.alpha.kubernetes.io/target: mc-router.thefryer.games
      gatus.home-operations.com/endpoint: |-
        group: services
      mc-router.itzg.me/externalServerName: *hostname
    minecraftServer:
      difficulty: "hard"
      eula: "true"
      forcegameMode: true
      maxPlayers: 10
      maxWorldSize: 29999984
      memory: "75%"
      motd: "The Fryer's Minecraft Server"
      ops: "FryyourBacon"
      overrideServerProperties: true
      removeOldMods: true
      spawnProtection: 0
      type: "FABRIC"
      # renovate: datasource=custom.minecraft-release depName=minecraft
      version: "26.2"
      viewDistance: 12
      modrinth:
        projects:
          - c2me-fabric:alpha
          - debugify
          - ferrite-core
          - krypton
          - lithium
          - packet-fixer
          - scalablelux
          - spark
        downloadDependencies: required
        allowedVersionType: release
      rcon:
        enabled: true
        existingSecret: &secret minecraft-secret
        secretKey: RCON_PASSWORD
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft
    extraVolumes:
      - volumeMounts:
          - name: vanillatweaks
            mountPath: /config/vanillatweaks
            readOnly: true
        volumes:
          - name: vanillatweaks
            configMap:
              name: minecraft-vanillatweaks
    extraEnv:
      ALLOW_FLIGHT: "true"
      ENABLE_ROLLING_LOGS: "true"
      ENFORCE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      RCON_CMDS_STARTUP: |-
        gamerule minecraft:fire_spread_radius_around_player 0
        gamerule minecraft:players_sleeping_percentage 0
        scoreboard objectives setdisplay list ts_Deaths
      SIMULATION_DISTANCE: "8"
      SNOOPER_ENABLED: "false"
      SYNC_CHUNK_WRITES: "false"
      USE_MEOWICE_FLAGS: "true"
      USE_MEOWICE_GRAALVM_FLAGS: "true"
      VANILLATWEAKS_FILE: "/config/vanillatweaks/vt-datapacks.json,/config/vanillatweaks/vt-craftingtweaks.json"
      WHITELIST:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: WHITELIST
    resources:
      requests:
        cpu: 500m
        memory: &mem 6Gi
      limits:
        memory: *mem
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
