---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: zfs-exporter
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      zfs-exporter:
        type: statefulset
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/mirceanton/zfs-exporter
              tag: 2.3.12@sha256:7eb88fff982c239b9b3c52429e771b859e3c944ca41808be0fd6194eab3f1e6f
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    service:
      app:
        ports:
          http:
            port: 9134
    serviceMonitor:
      app:
        serviceName: zfs-exporter
        endpoints:
          - port: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
    persistence:
      dev-zfs:
        type: hostPath
        hostPath: /dev/zfs
        globalMounts:
          - path: /dev/zfs
