---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zfs-exporter
spec:
  groups:
    - name: zfs.rules
      rules:
        - alert: ZfsExporterAbsent
          annotations:
            summary: ZFS exporter is not being scraped.
          expr: absent(up{job=~".*zfs-exporter.*"})
          for: 10m
          labels:
            severity: critical
        - alert: ZfsPoolDegraded
          annotations:
            summary: ZFS pool {{ $labels.pool }} is degraded.
          expr: zfs_pool_health == 1
          for: 5m
          labels:
            severity: warning
        - alert: ZfsPoolUnhealthy
          annotations:
            summary: ZFS pool {{ $labels.pool }} is unhealthy.
          expr: zfs_pool_health > 1
          for: 2m
          labels:
            severity: critical
        - alert: ZfsPoolReadOnly
          annotations:
            summary: ZFS pool {{ $labels.pool }} is read-only.
          expr: zfs_pool_readonly == 1
          for: 2m
          labels:
            severity: critical
        - alert: ZfsPoolCapacityWarning
          annotations:
            summary: ZFS pool {{ $labels.pool }} is more than 80% full.
          expr: zfs_pool_capacity_ratio > 0.80
          for: 10m
          labels:
            severity: warning
        - alert: ZfsPoolCapacityCritical
          annotations:
            summary: ZFS pool {{ $labels.pool }} is more than 90% full.
          expr: zfs_pool_capacity_ratio > 0.90
          for: 5m
          labels:
            severity: critical
