---
- name: Create Portainer-agent folder.
  ansible.builtin.file:
    path: "{{ config_dir }}/portainer-agent"
    state: directory
    mode: "0755"
  become: false
  register: portainer_agent_dir

- name: Copy Portainer-agent docker-compose template to server.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ portainer_agent_dir.path }}/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart portainer-agent

- name: Ensure Portainer-agent is running.
  community.docker.docker_compose:
    project_src: "{{ portainer_agent_dir.path }}/"
  become: false
