---
- name: Create jobs
  become: false
  community.general.nomad_job:
    host: dingdongs
    state: present
    content: "{{ lookup('ansible.builtin.template', '{{ item }}') }}"
    timeout: 120
    validate_certs: false
  with_fileglob:
    - "roles/jobs/templates/*.nomad.j2"
  delegate_to: localhost
  run_once: true
