---
- name: Install on specific node
  vars:
    install_node: "houseco-2"
    archisteamfarm_config_dir: /var/data/config/archisteamfarm
  block:
    - name: Ensure config directory exists
      when: inventory_hostname == install_node
      ansible.builtin.file:
        path: "{{ archisteamfarm_config_dir }}"
        recurse: true
    - name: Copy IPC config
      when: inventory_hostname == install_node
      ansible.builtin.copy:
        src: IPC.config
        dest: "{{ archisteamfarm_config_dir }}"
        owner: 1000
        mode: "0600"
    - name: Copy ASF config
      when: inventory_hostname == install_node
      ansible.builtin.template:
        src: ASF.json.j2
        dest: "{{ archisteamfarm_config_dir }}/ASF.json"
        owner: 1000
        mode: "0600"
    - name: Deploy Stacks
      when: inventory_hostname == play_hosts[0]
      community.docker.docker_stack:
        state: present
        name: archisteamfarm
        compose:
          - services:
              archisteamfarm:
                image: justarchi/archisteamfarm:5.4.3.2
                volumes:
                  - "{{ archisteamfarm_config_dir }}:/app/config"
                networks:
                  - traefik_public
                deploy:
                  mode: replicated
                  replicas: 1
                  labels:
                    - "traefik.docker.network=traefik_public"
                    - "traefik.http.routers.archisteamfarm.rule=Host(`archisteamfarm.caycehouse.com`)"
                    - "traefik.http.routers.archisteamfarm.entrypoints=https"
                    - "traefik.http.services.archisteamfarm.loadbalancer.server.port=1242"
                    - "traefik.enable=true"
                  placement:
                    constraints:
                      - node.hostname == {{ install_node }}
          - networks:
              traefik_public:
                external: true
                driver_opts:
                  com.docker.network.driver.mtu: 1280
