apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:X4ZsY4H2oATINFelSMUUdorL3ELOkoEzajbNhT2L5YCFjwUY3C0vkQ==,iv:aH+pIKBhf6OKbcfCAMtk16jGzd3QV5+gPHEhuc54TiE=,tag:PcCnTBFIkzh/Bq56WLauFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19g8y23904c6pcwuqpldhke2vdrfwlyq3vh685llzf2xg8ntd3u6su59vxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRzYzcVFoYjdrUjREdjg4
            RGxiQ0w4VDJmK1d3TjRQTXhUa2tCRk5BcUIwCmdaNTZGR2NvNDdIRlk0bVBib2di
            REJpV3RSbWZYRUJYcFlFTE0vV1lMaHcKLS0tIEpSWDVCeU1kcGt1Z3NGZ0lvSzZQ
            NFNhNmpXZzh1RU92ay9rMFRVc0NOUG8KLwrmhZ77dCDsuutrsyx65nX1DamMAbg4
            8ohec231WMX7fqFDTaM4X47nhDqzA1JZCPHu5lSvp5d/R9YiWRVpcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:38:54Z"
    mac: ENC[AES256_GCM,data:UY5Hx/XxvOh9s+TEiLtfvdVoCjWHOCiNl3cZP2GKcM5IvhjhQuUXzgyJHuJypC0SyiZnm7cBDzfqmgwGYrKoxgIu1zVYDnfy77bCMKHWpj5n7IhYYyuB4EH9F/zTgjQSqAOJlJa9++QzO2fLROsDAEwk7BPPx4V0gTkeHPprka8=,iv:kg3O/RWJHfSTa1AIhoNMdlXt2FXYNPDdlDuRcToYe10=,tag:0aea9Gg2QYMoFzYJRLK1/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
