{
 "title": "MikroTik Dashboard",
 "description": "Mikrotik monitoring (9.4.7)",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrSerialNumber{instance='$instance'}",
     "legendFormat": "{{mtxrSerialNumber}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "CPU Core {{hrDeviceIndex}}"
    },
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})",
     "legendFormat": "CPU Avg"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "Memory"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "System identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysIdentity{instance='$instance'}",
     "legendFormat": "{{sysIdentity}}"
    }
   ]
  },
  {
   "title": "System date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(hrSystemDate{instance='$instance'})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "Upgrade Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrFirmwareUpgradeVersion{instance='$instance'}",
     "legendFormat": "{{mtxrFirmwareUpgradeVersion}}"
    }
   ]
  },
  {
   "title": "Board ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrBuildTime{instance='$instance'}",
     "legendFormat": "{{mtxrBuildTime}}"
    }
   ]
  },
  {
   "title": "Board ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrFirmwareVersion{instance='$instance'}",
     "legendFormat": "{{mtxrFirmwareVersion}}"
    }
   ]
  },
  {
   "title": "Package ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrLicVersion{instance='$instance'}",
     "legendFormat": "{{mtxrLicVersion}}"
    }
   ]
  },
  {
   "title": "Software ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicSoftwareId{instance='$instance'}",
     "legendFormat": "{{mtxrLicSoftwareId}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    {
     "expr": "ifHighSpeed{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    },
    { "expr": "ifMtu{instance='$instance'}" },
    {
     "expr": "ifType_info{instance='$instance'}"
    },
    {
     "expr": "mtxrPOEInterfaceIndex{instance='$instance'}"
    },
    { "expr": "ifAlias{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsTxFCSError{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxFCSError{instance='$instance'}"
    }
   ]
  },
  {
   "title": "WAN and VPN Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAN Traffic",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ifHCOutOctets{ifName=~'sfp28-12',instance='$instance'}",
       "legendFormat": "Out - {{ifName}}"
      },
      {
       "expr": "ifHCInOctets{ifName=~'sfp28-12',instance='$instance'}",
       "legendFormat": "In - {{ifName}}"
      },
      {
       "expr": "(ifHCOutOctets{ifName=~'sfp28-12',instance='$instance'})+(ifHCInOctets{ifName=~'sfp28-12',instance='$instance'})",
       "legendFormat": "Total - {{ifName}}"
      }
     ]
    },
    {
     "title": "WAN Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'sfp28-12',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In - {{ifName}}"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'sfp28-12',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out - {{ifName}}"
      }
     ]
    },
    {
     "title": "IPSEC Tunnel Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'IPSEC',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In- {{ifName}}"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'IPSEC',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out - {{ifName}}"
      }
     ]
    },
    {
     "title": "IPSEC Tunnel Traffic",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ifHCOutOctets{ifName=~'IPSEC',instance='$instance'}",
       "legendFormat": "Out - {{ifName}}"
      },
      {
       "expr": "ifHCInOctets{ifName=~'IPSEC',instance='$instance'}",
       "legendFormat": "In - {{ifName}}"
      },
      {
       "expr": "(ifHCOutOctets{ifName=~'IPSEC',instance='$instance'})+(ifHCInOctets{ifName=~'IPSEC',instance='$instance'})",
       "legendFormat": "Total - {{ifName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic (all)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Optic Tx/Rx Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalTxPower{instance='$instance',mtxrOpticalIndex=\"21\"}/1000",
     "legendFormat": "sfp28-12 - Tx Power"
    },
    {
     "expr": "mtxrOpticalRxPower{instance='$instance',mtxrOpticalIndex=\"21\"}/1000",
     "legendFormat": "sfp28-12 - Rx Power"
    },
    {
     "expr": "mtxrOpticalTxPower{instance='$instance',mtxrOpticalIndex=\"17\"}/1000",
     "legendFormat": "sfp28-8 - Tx Power"
    },
    {
     "expr": "mtxrOpticalRxPower{instance='$instance',mtxrOpticalIndex=\"17\"}/1000",
     "legendFormat": "sfp28-8 - Rx Power"
    }
   ]
  },
  {
   "title": "Optic Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalTemperature{instance='$instance',mtxrOpticalIndex=\"21\"}",
     "legendFormat": "sfp28-12 - Tx Power"
    },
    {
     "expr": "mtxrOpticalTemperature{instance='$instance',mtxrOpticalIndex=\"17\"}",
     "legendFormat": "sfp28-8 - Rx Power"
    }
   ]
  },
  {
   "title": "Optic Supply Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalSupplyVoltage{instance='$instance',mtxrOpticalIndex=\"21\"}/1000",
     "legendFormat": "sfp28-12 - Tx Power"
    },
    {
     "expr": "mtxrOpticalSupplyVoltage{instance='$instance',mtxrOpticalIndex=\"17\"}/1000",
     "legendFormat": "sfp28-8 - Rx Power"
    }
   ]
  },
  {
   "title": "Optic Wavelength",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "nanometer" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalWavelength{instance='$instance',mtxrOpticalIndex=\"21\"}/100",
     "legendFormat": "sfp28-12 - Tx Power"
    },
    {
     "expr": "mtxrOpticalWavelength{instance='$instance',mtxrOpticalIndex=\"17\"}/100",
     "legendFormat": "sfp28-8 - Rx Power"
    }
   ]
  },
  {
   "title": "Interfaces Traffic Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Traffic \"$Interface\"",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "-irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "*cast/Dascard/Errors/Unknown Protos/Queue length",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Interface \"$Interface\"",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 44 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "-irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "-irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "-irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "-irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total SNMP time (walk and processing)",
     "type": "stat",
     "description": "Total SNMP time scrape took (walk and processing)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Time SNMP walk/bulkwalk took",
     "type": "stat",
     "description": "Time SNMP walk/bulkwalk took",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
      }
     ]
    },
    {
     "title": "scrape pdus returned",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
      }
     ]
    }
   ]
  }
 ]
}