---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  image: ghcr.io/berriai/litellm:v1.93.0-rc.1@sha256:2fdd90b14e3d9244ce297f418b983d8cfd90ba6e72a10a8ddb30f7cf64852390
  generalSettings:
    health_check_endpoint: /v1/health
  envFrom:
    - secretRef:
        name: litellm-secret
  route:
    hostnames:
      - litellm.housefam.casa
    parentRefs:
      - name: envoy-internal
        namespace: network
  resources:
    requests:
      cpu: 25m
    limits:
      memory: 4Gi
