---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  image: ghcr.io/berriai/litellm:v1.97.0@sha256:468c25f35f3e5ec4e414974f00deab93337b1b4d9953cabcfd3722e59415f834
  generalSettings:
    health_check_endpoint: /v1/health
  envFrom:
    - secretRef:
        name: litellm-secret
  route:
    hostnames:
      - litellm.housefam.casa
    parentRefs:
      - name: envoy-internal
        namespace: network
  resources:
    requests:
      cpu: 25m
    limits:
      memory: 4Gi
