---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  image: ghcr.io/berriai/litellm:v1.99.1@sha256:a53a7d3ffebede1925bd3ee8a21e4a7b9b63e2e68ec883af136edcccb6eeb82c
  generalSettings:
    health_check_endpoint: /v1/health
  envFrom:
    - secretRef:
        name: litellm-secret
  route:
    hostnames:
      - litellm.housefam.casa
    parentRefs:
      - name: envoy-internal
        namespace: network
  resources:
    requests:
      cpu: 25m
    limits:
      memory: 4Gi
