---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s3-kopia-sync
spec:
  chartRef:
    kind: OCIRepository
    name: s3-kopia-sync
  interval: 1h
  values:
    controllers:
      s3-kopia-sync:
        type: cronjob
        cronjob:
          schedule: "0 4 * * *"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/kopia
              tag: 0.22.3@sha256:17ab64542280197a5368247deaefadc3e3bbe15714ab666c2455a06824e86efd
            command:
              - /scripts/sync.sh
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    configMaps:
      config:
        data:
          repository.config: |-
            {
              "storage": {
                "type": "filesystem",
                "config": {
                  "path": "/repository"
                }
              },
              "hostname": "s3-kopia-sync.{{ .Release.Namespace }}.svc.cluster.local",
              "username": "s3-kopia-sync",
              "description": "s3-kopia-sync",
              "enableActions": false,
              "readonly": true
            }
    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/repository.config
            subPath: repository.config
      repository:
        type: nfs
        server: unas-2.internal
        path: /var/nfs/shared/Kopia
        globalMounts:
          - path: /repository
      script:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - subPath: sync.sh
            path: /scripts/sync.sh
        defaultMode: 0777
      tmpfs:
        type: emptyDir
        advancedMounts:
          s3-kopia-sync:
            app:
              - path: /config/cache
                subPath: cache
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
