---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twitchdropsminer
spec:
  chartRef:
    kind: OCIRepository
    name: twitchdropsminer
  interval: 1h
  values:
    controllers:
      twitchdropsminer:
        containers:
          app:
            image:
              repository: mirror.gcr.io/dungfu/twitch-drops-miner
              tag: webui@sha256:a599c0dce5d8da66e3f306c00a938c900c3cbaa7d79742d980b0314509a11ecf
            env:
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      hostUsers: false
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.housefam.casa"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /TwitchDropsMiner/config
      cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /TwitchDropsMiner/cache
