---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Restart qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: restarted

- name: Reboot
  ansible.builtin.reboot:
