---
- name: Change proxmox repository from pve-enterprise to pve-no-subscription
  block:
    - name: Add pve-no-subscription repository
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
        state: present
        update_cache: false

    - name: Remove pve-enterprise repository
      ansible.builtin.apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
        state: absent
        update_cache: false

    - name: Update pkg cache and dist-upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

- name: Ensure root login is enabled
  block:
    - name: Enable root login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: ^PermitRootLogin
        line: PermitRootLogin yes
        validate: sshd -t -f %s
      notify: Restart sshd

- name: Install tailscale cert
  block:
    - name: Install pre-reqs
      ansible.builtin.package:
        name: jq
        state: present

    - name: Install cert
      ansible.builtin.copy:
        src: renew-tailscale-cert.sh
        dest: /root/renew-tailscale-cert.sh
        mode: '0744'
      register: script

    - name: Run once for initial creation
      ansible.builtin.shell: /root/renew-tailscale-cert.sh
      args:
        chdir: /etc/ssl/private
      when: script.changed

    - name: Set weekly cron to renew Tailscale cert
      ansible.builtin.cron:
        name: "renew Tailscale cert weekly"
        minute: "0"
        hour: "0"
        weekday: "0"
        job: "/root/renew-tailscale-cert.sh"
