---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rtlamr2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rtlamr2mqtt-secret
    template:
      data:
        rtlamr2mqtt.yaml: |
          general:
            sleep_for: 0
            verbosity: debug
            device_id: 0
            listen_mode: false
          mqtt:
            host: mosquitto.default.svc.cluster.local
            port: 1883
            tls_enabled: false
            ha_autodiscovery_topic: homeassistant
            ha_status_topic: homeassistant/status
            base_topic: rtlamr
          custom_parameters:
            rtlamr: -unique=true -symbollength=32
          meters:
            - id: "{{ .RTLAMR2MQTT_GAS_METER_ID }}"
              protocol: scm+
              name: gas_meter
              device_class: gas
              unit_of_measurement: CCF
              state_class: total_increasing
              format: "#####.#"
            - id: "{{ .RTLAMR2MQTT_ELECTRIC_METER_ID }}"
              protocol: idm
              name: electric_meter
              device_class: energy
              unit_of_measurement: kWh
              state_class: total_increasing
              format: "######.##"
  dataFrom:
    - extract:
        key: rtlamr2mqtt
