apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:bTT3iCBNhjRbXoD1B7EtRxZNlm42+ZQCOxEE3/9Y95qlYAuHWg==,iv:bJB6n8bvbHki7aMy15XwMbTx5lJElRI+2x28hXUJWSs=,tag:WAfpnPNaQtb425StpvHaYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19g8y23904c6pcwuqpldhke2vdrfwlyq3vh685llzf2xg8ntd3u6su59vxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bi9aQnpiQ1JkcVhXQzc2
            YzVyTjBORDNQYmVuT0hSZnlrTys5UFh2bzA4CkZub1RnN2RsSXQ1bnRFcFByanps
            WXlSU010SlZqc0VYc2IwdEhLakJqZDQKLS0tIDZiUkdyVGpBdWJqNHRPTllIbzRO
            elFGcG9zcGlpbUplZ1hpWFQ2Vmg5VlkK8Z88PNFYadeCtw9ezrhod/XLTVGlkBEe
            zP5vDxIyUsXwrn05FHQUyfcN8jGWO98Bq+C+t4E1F6hRzNthSZdGDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:30:50Z"
    mac: ENC[AES256_GCM,data:iagEloJOKqadKiObb2J/vODJg+YYiVYweJgoDqrHuXiqbaZHf9YvYSeicAFE2l8FgxDYgiYknuew4V8Fg+BY+3+D4u7czlU5ugp8QL7QEkYDkJDlqLH+dkoJzJxsbFMbXagqIim/kluBQ1sgIgSVrwtHph16GvNbDj2VxCu5Udc=,iv:hDzyNdODyx61CAjGxgbXWGvKJBt33wZeoAvYYmNY5jU=,tag:uxgYY4r4rxLW8ztcnzmXyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
