---
- name: Install on specific node
  vars:
    install_node: "cleverhouse-1"
  block:
    - name: Create needed dir
      when: inventory_hostname == install_node
      ansible.builtin.file:
        path: /var/data/atm8
        recurse: true
    - name: Deploy Stacks
      when: inventory_hostname == play_hosts[0]
      community.docker.docker_stack:
        state: present
        name: atm8
        compose:
          - services:
              atm8:
                image: itzg/minecraft-server:2023.1.0-java17
                ports:
                  - 25566:25565
                environment:
                  CF_FILE_ID: "4415465"
                  CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
                  EULA: "TRUE"
                  TYPE: AUTO_CURSEFORGE
                  MEMORY: "4G"
                  USE_AIKAR_FLAGS: "true"
                volumes:
                  - /var/data/atm8:/data
                healthcheck:
                  test: mc-health
                  start_period: 7m
                  interval: 5s
                  retries: 20
                deploy:
                  mode: replicated
                  replicas: 1
                  resources:
                    limits:
                      memory: 6G
                    reservations:
                      memory: 4G
                  placement:
                    constraints:
                      - node.hostname == {{ install_node }}
          - networks:
              internal:
                driver: overlay
                driver_opts:
                  com.docker.network.driver.mtu: 1280
                ipam:
                  config:
                    - subnet: 172.16.24.0/24
