apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:OgpLZFpe+Zg33fPlCZuO4mzmy4U=,iv:JAUPp2M3cpXLgLkg7YfVRnfrQiSixhEN5l3jRa/84aI=,tag:t9dCuE1cnyIRnvzE/EpyAw==,type:str]
    api-key: ENC[AES256_GCM,data:t4vW1RFqyrjG5EpP34jJQtCb0AN/z5dulhaJT2qp+ubHgwqRKA==,iv:Vz9t52Ej2rqBod4ci6mGBOR4Gphm7VO2vB/vHnSFJDs=,tag:pCDRsHwx5tOmIF0g95Cgpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19g8y23904c6pcwuqpldhke2vdrfwlyq3vh685llzf2xg8ntd3u6su59vxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOUhxK3dXdXpqUy80enlK
            dDlYNlovMEEvNUE1NktLY3dDSTF1a0hLeGo0Ck84NEVxYnhQMWQ0YWdvQnMzTG9Q
            ZWJzSGxhR2FQb3pvek1hL0VSeXkvYmsKLS0tIEVYRWV0MGsrUlYzb0ZscXk3c0Nv
            bVAxRkQ4SE1ac0lySTI1QzRDeUcrVkkKe0XJE21Wkd/+vTCKBwKJ0lPIB80QD4Tv
            AIllV1qIVDxuILDZbB2U8yLft77DEmTS3dno/Y6Rz+GJsswb/EXvVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:34:04Z"
    mac: ENC[AES256_GCM,data:/En1utGTp+G6yVIQIfVtSgQcUi6dzXvF6rHqP7ykQ+8kADSua3C3Ana0GIdcTEyA3L4vi4qhLC5dTI35sL16np7C7PaBo/Hh2Nugq/ClMFsHddiTWvglL4eSJJjnW3cW1EeOBUc5hfsmzMBjn8iJpeGhztGmCtru+lZQQvI1zfI=,iv:2627ihty8LvwTuEKuICoh3ipFZPJ8malM1NT6e69Wjc=,tag:HmTzgudiGw5z+hAMCPpU3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
