---
- name: Create folder for {{ service }}
  ansible.builtin.file:
    path: "{{ config_dir }}/{{ service }}"
    state: directory
    mode: "0755"
  become: false
  register: service_dir

- name: Generate docker-compose template for {{ service }}
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "/tmp/docker-compose-{{ service }}.yml"
    mode: "0640"
  become: false
  delegate_to: localhost
  register: template

- name: Copy docker-compose template to server for {{ service }}
  ansible.builtin.copy:
    src: "/tmp/docker-compose-{{ service }}.yml"
    dest: "{{ service_dir.path }}/docker-compose.yml"
    mode: "0640"
  become: false
  when: template.changed

- name: Start {{ service }}
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir.path }}/"
    remove_orphans: true
  become: false
  when: start

- name: Stop {{ service }}
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir.path }}/"
    remove_orphans: true
    state: stopped
  become: false
  when: not start
