services:
  free-games-claimer:
    container_name: fgc
    image: ghcr.io/vogler/free-games-claimer:latest@sha256:5159604eff840b75e75293f90c11f733d20ab4cab3d9f2369f2c3a854705cff0
    volumes:
      - fgc:/fgc/data
    environment:
      - EMAIL=$EMAIL
      - EG_PASSWORD=$EG_PASSWORD
      - EG_OTPKEY=$EG_OTPKEY
      - PG_PASSWORD=$PG_PASSWORD
      - PG_OTPKEY=$PG_OTPKEY
      - PG_REDEEM=1
      - GOG_PASSWORD=$GOG_PASSWORD
      - NOTIFY=$NOTIFY
    networks:
      - traefik_public
    labels:
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.fgc.rule=Host(`fgc.caycehouse.com`)"
      - "traefik.http.routers.fgc.entrypoints=websecure"
      - "traefik.http.services.fgc.loadbalancer.server.port=6080"
      - "traefik.enable=true"
networks:
  traefik_public:
    external: true
volumes:
  fgc:
