---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./litellm/ks.yaml
  - ./litellm-operator/ks.yaml
  - ./ha-mcp/ks.yaml
  - ./actual-mcp/ks.yaml
  - ./flux-operator-mcp/ks.yaml
  - ./grafana-mcp/ks.yaml
  - ./victoria-logs-mcp/ks.yaml
  - ./konflate-mcp/ks.yaml
  - ./unifi-mcp/ks.yaml
