---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-mcp-secret
    template:
      data:
        ACTUAL_PASSWORD: "{{ .ACTUAL_PASSWORD }}"
        ACTUAL_BUDGET_SYNC_ID: "{{ .ACTUAL_BUDGET_SYNC_ID }}"
        MCP_SSE_AUTHORIZATION: "{{ .MCP_SSE_AUTHORIZATION }}"
  dataFrom:
    - extract:
        key: actual-mcp
