---
- name: Play for docker nodes
  hosts: docker_nodes
  tasks:
    - name: Include roles based on docker_compose_roles
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags:
            - "{{ item }}"
            - "compose"
      tags: always
      loop: "{{ docker_compose_roles }}"
