# Example usage: ansible-playbook state.yml
# This playbook deploys my whole homelab.
---
- name: Play for all machines
  hosts: all
  roles:
    - {role: common, tags: common}
    - {role: artis3n.tailscale, tags: tailscale}

- name: Play to add swap to needed machines
  hosts: all,!proxmox_servers,!octopi
  roles:
    - {role: geerlingguy.swap, tags: swap}

- name: Play for proxmox machines
  hosts: cupcakes
  roles:
    - {role: proxmox, tags: proxmox}

- name: Play for docker nodes
  hosts: docker_nodes
  roles:
    - {role: geerlingguy.pip, tags: pip}
    - {role: geerlingguy.docker, tags: docker}
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present
      tags: docker-swarm
