apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:GFfqCpz6o8VKcY1I0XBq7PRGcAE9Ab6GieM0fc2DnXG5CmAs7Vd/2mzEPT4j4Sgfc+dUqFKVkSDWKbNo,iv:klUdAy3Esj1/HFzpZWIvTxxj4XQdA/X8nVQud84nMVY=,tag:e27cCvf54GT+2inDWkfgCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19g8y23904c6pcwuqpldhke2vdrfwlyq3vh685llzf2xg8ntd3u6su59vxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y3JDY0U5OHNNRjBoWnFi
            cHRRR01PRXJhQmtOL2dxR1M5L2toVlFYYlNVClhqdFhDcUdOZ1VrdHpaZS9td21T
            bXJKUkY2Y0ZRbGxhTXFKTmxLN1dSY3cKLS0tIGZmdzlLRlZ6VlFZU1pOaG1DM0cy
            dzZuNThxNkpFL2gyK0hYVk9zc1BtMUkKSbtRCKvjHcmiwj0brZYbL+v3h+NT/Lha
            0b0UFcZFhoV8FdpgtUyKZd69gMFwvrxOqxcZYSZUtHSfFj5hNXiPZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:39:57Z"
    mac: ENC[AES256_GCM,data:fSXuMsOiqe20V3evMrb7kbayB6oi5C3KtKe9/mF8EOQkAVdlJf1bPcLSgcM5H3G4PuRHwkjJS8PA8AbiwXjEDDC7HEx/y8GSGjvdByBOaJw+E8EYhEkJ8dqNmwFCYWDDPZHlgCDfsMPIxminJnwMEbNS12jGArfG+/MiDkYMK3Y=,iv:Z1p6/6w3RRA6RCPYE1Ies5156xzXD12jEZVhBgJM+v4=,tag:VRmUUrjj5tSc3V9zd5cBxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
