---
- name: Add Hashicorp apt repository key.
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: '0644'
    force: true

- name: Add Hashicorp apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: "hashicorp"
    state: present
    update_cache: true

- name: Install nomad
  ansible.builtin.apt:
    pkg:
      - nomad

- name: Copy nomad base config file
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0640
  notify: Restart nomad

- name: Copy ca cert
  ansible.builtin.copy:
    src: nomad-ca.pem
    dest: /etc/nomad.d/
    owner: nomad
    group: nomad
    mode: 0600
  notify: Restart nomad

- name: Copy server certs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/nomad.d/
    owner: nomad
    group: nomad
    mode: 0600
  loop:
    - server.pem
    - server-key.pem
  when: "'nomad_server' in group_names"
  notify: Restart nomad

- name: Ensure agents do not have certs
  ansible.builtin.file:
    path: "/etc/nomad.d/{{ item }}"
    state: absent
  loop:
    - server.pem
    - server-key.pem
  when: "'nomad_agents' in group_names"

- name: Copy client certs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/nomad.d/
    owner: nomad
    group: nomad
    mode: 0600
  loop:
    - client.pem
    - client-key.pem
  when: "'nomad_agents' in group_names"
  notify: Restart nomad

- name: Ensure servers do not have client certs
  ansible.builtin.file:
    path: "/etc/nomad.d/{{ item }}"
    state: absent
  loop:
    - client.pem
    - client-key.pem
  when: "'nomad_server' in group_names"

- name: Ensure proper permissions
  ansible.builtin.file:
    path: /etc/nomad.d
    owner: nomad
    group: nomad
    recurse: true
  notify: Restart nomad

- name: Enable nomad
  ansible.builtin.service:
    name: nomad
    enabled: true
    state: started
