---
- name: Install on specific node
  vars:
    install_node: "bakery"
    satisfactory_config_dir: /var/data/config/satisfactory
    satisfactory_runtime_dir: /var/data/runtime/satisfactory
  block:
    - name: Create needed dir
      when: inventory_hostname == install_node
      ansible.builtin.file:
        path: "{{ item }}"
        recurse: true
      loop:
        - "{{ satisfactory_config_dir }}"
        - "{{ satisfactory_runtime_dir }}"
    - name: Deploy Stacks
      when: inventory_hostname == play_hosts[0]
      community.docker.docker_stack:
        state: present
        name: satisfactory
        compose:
          - services:
              satisfactory:
                image: wolveix/satisfactory-server:v1.4.6
                environment:
                  AUTOPAUSE: "false"
                volumes:
                  - "{{ satisfactory_config_dir }}:/config"
                  - "{{ satisfactory_runtime_dir }}:/gamefiles"
                ports:
                  - 7777:7777/udp
                  - 15000:15000/udp
                  - 15777:15777/udp
                deploy:
                  mode: replicated
                  replicas: 1
                  resources:
                    limits:
                      memory: 16G
                    reservations:
                      memory: 12G
                  placement:
                    constraints:
                      - node.hostname == {{ install_node }}
