---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: free-games-claimer
spec:
  chartRef:
    kind: OCIRepository
    name: free-games-claimer
  interval: 1h
  values:
    controllers:
      free-games-claimer:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/feldorn/free-games-claimer
              tag: latest@sha256:b5bd509d39d0e7920ca2027074f3542c66cd4669ab1453aca25c806eb6cd4e05
            env:
              LOOP: "86400"
              NOVNC_PORT: &novncPort 6080
              NOVNC_URL: https://fgc-vnc.housefam.casa
              PANEL_PORT: &port 80
              PG_CLAIMDLC: "1"
              PG_REDEEM: "1"
              PUID: "1000"
              PGID: "1000"
              PUBLIC_URL: https://fgc.housefam.casa
              START_TIME: "12:00"
              TZ: America/New_York
              UPDATE_CHECK: "0"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    service:
      app:
        primary: true
        ports:
          http:
            port: *port
      novnc:
        ports:
          http:
            port: *novncPort
    route:
      app:
        hostnames:
          - fgc.housefam.casa
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      novnc:
        hostnames:
          - fgc-vnc.housefam.casa
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: novnc
                port: *novncPort
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /fgc/data
