# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/batch/job_v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: free-games-claimer-pvc-init
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: init
          image: ghcr.io/home-operations/busybox:1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
          command: ["/bin/sh", "-c", "echo pvc ready"]
          volumeMounts:
            - name: data
              mountPath: /fgc/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: free-games-claimer
