apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VD3uqcxqiXYtDkEEkG4=,iv:CnhWYez8G8BTT5kvF8ypu0c3mYNZWq1QWVZGUOpN9gw=,tag:2iJ8yC/Vxmt863as9tNXxg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PUtdD2czQPdFSKWScP5mcftkutA=,iv:2R6ADSdHfeqk+xLmhfM/bMPWwQetxPw+aq60s+chsvY=,tag:cl0M4dM/LrBp/g3UPHAJ6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19g8y23904c6pcwuqpldhke2vdrfwlyq3vh685llzf2xg8ntd3u6su59vxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU2hFYWRvdEhIZFc5ZER3
            VytTTldmbjdwczFQQmdNSUJmZDlwT3NHUzBRClN0VlZXdWhQTU9oeTF3NkpzcTEr
            YWpqVkVhcmF2QkFsUmd4c0N4R08wM1EKLS0tIENYeHZFT2ZRd25EUXZBUzluVlFJ
            U2YwY3pESml3Zi9kcEFpUmNvTGFsNVEKUQe57d6e8iwN2on0aiF828T+zyy99InA
            mA9EEQaoT86DPxSkGWGDHK2ItaFEQrfJNxm5uBYz/GF69u9emUs3dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:28:07Z"
    mac: ENC[AES256_GCM,data:p2xsTG5woMFGsNmAm0+tVqoq/KZDLLJFp7OXAzfk7ciyCS1sQC6teX2SzmjgmuOpTlSlqsrrquA75v/OgTE4cVP5FawuWLqGmuBUf3b9ipCu2abE0yf54VqUDnyQC1Q2yOuC475v5ZRh7ICEE1m8/9GNt+C+CGDa2NMa5FQEeck=,iv:IDGgIKM6+zWoMkmjqUHyycCNX9gQjJtnEvI5jasxLxs=,tag:dPbyu94VD/VhHNs7y5WtMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
