services:
  archisteamfarm:
    image: justarchi/archisteamfarm:5.4.3.2
    volumes:
      - data:/app/config
    networks:
      - traefik_public
    labels:
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.archisteamfarm.rule=Host(`asf.caycehouse.com`)"
      - "traefik.http.routers.archisteamfarm.entrypoints=https"
      - "traefik.http.services.archisteamfarm.loadbalancer.server.port=1242"
      - "traefik.enable=true"
networks:
  traefik_public:
    external: true
volumes:
  data:
