---
tailscale_args: "--ssh"
tailscale_oauth_ephemeral: false
tailscale_oauth_preauthorized: true
tailscale_tags:
  - "server"

swap_file_size_mb: "8192"
swap_swappiness: "1"

pip_install_packages:
  - docker
docker_daemon_options:
  log-driver: "local"
  mtu: 1280
docker_users:
  - caycehouse
config_dir: "~"

user_id: 1000
group_id: 1000
