---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: &name grafana-mcp
spec:
  name: *name
  instanceName: grafana
  role: Viewer
  isDisabled: false
  tokens:
    - name: mcp
      secretName: *name
