---
- name: Update APT cache and upgrade packages
  block:
    - name: Perform a dist-upgrade (this may take a while).
      ansible.builtin.apt:
        upgrade: dist
        cache_valid_time: 3600
      ignore_unreachable: true

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: false
      register: reboot_required_file

    - name: Reboot the server (if required) and prevent_reboot != true.
      ansible.builtin.reboot:
      when: (reboot_required_file.stat.exists) and
        (hostvars[inventory_hostname].prevent_reboot is not defined)

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: true
