---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopia-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        repository.config: |
          {
            "storage": {
              "type": "s3",
              "config": {
                "bucket": "volsync-kopia",
                "endpoint": "{{ .AWS_S3_ENDPOINT }}",
                "accessKeyID": "{{ .AWS_ACCESS_KEY_ID }}",
                "secretAccessKey": "{{ .AWS_SECRET_ACCESS_KEY }}"
              }
            },
            "hostname": "volsync.volsync-system.svc.cluster.local",
            "username": "volsync",
            "description": "volsync",
            "enableActions": false
          }
  dataFrom:
    - extract:
        key: volsync-template
