---
docker_compose_roles:
  # home-ops services
  - cloudflared
  - portainer
  - portainer-agent
  - restic

  # Apps
  - allinone
  - archisteamfarm
  - atm8
  - calibre
  - changedetection
  - cloudflare-ddns
  - code-server
  - free-games-claimer
  - homepage
  - minecraft
  - miniflux
  - monica
  - oceanblock
  - paperless-ngx
  - palworld
  - plexiglass-mountain
  - satisfactory
  - thethans
  - twitchdropsminer
  - uptime-kuma
  - valheim
