---
docker_compose_roles:
  - cloudflared
  - portainer
  - portainer-agent
  - restic
  - allinone
  - archisteamfarm
  - changedetection
  - free-games-claimer
  - homepage
  - minecraft
  - miniflux
  - monica
  - oceanblock
  - plexiglass-mountain
  - satisfactory
  - thethans
  - valheim
