---
- name: Install on specific node
  vars:
    install_node: "houseco-1"
  block:
    - name: Create needed dir
      when: inventory_hostname == install_node
      ansible.builtin.file:
        path: /var/data/traefik
        recurse: true

    - name: Create needed files
      when: inventory_hostname == install_node
      ansible.builtin.copy:
        content: ""
        dest: "{{ item }}"
        force: false
        mode: "0600"
      loop:
        - /var/data/traefik/acme.json
        - /var/data/traefik/traefik.log

    - name: Copy traefik config
      when: inventory_hostname == install_node
      ansible.builtin.copy:
        src: traefik.toml
        dest: /var/data/config/traefik/
        mode: "0600"

    - name: Create required swarm network
      when: inventory_hostname == play_hosts[0]
      community.docker.docker_network:
        name: traefik_public
        scope: swarm
        driver: overlay
        attachable: true
        ipam_config:
          - subnet: 172.16.200.0/24
        driver_options:
          com.docker.network.driver.mtu: 1280

    - name: Deploy Stacks
      when: inventory_hostname == play_hosts[0]
      community.docker.docker_stack:
        state: present
        name: traefik
        compose:
          - services:
              agent:
                image: traefik:v2.9
                environment:
                  CLOUDFLARE_EMAIL: "{{ traefik.cloudflare_email }}"
                  CLOUDFLARE_API_KEY: "{{ traefik.cloudflare_api_key }}"
                ports:
                  - 80:80
                  - 443:443
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
                  - /var/data/config/traefik:/etc/traefik
                  - /var/data/traefik/traefik.log:/traefik.log
                  - /var/data/traefik/acme.json:/acme.json
                networks:
                  - traefik_public
                deploy:
                  labels:
                    - "traefik.docker.network=traefik_public"
                    - "traefik.http.routers.traefik.rule=Host(`traefik.caycehouse.com`)"
                    - "traefik.http.routers.traefik.entrypoints=https"
                    - "traefik.http.routers.traefik.tls.domains[0].main=caycehouse.com"
                    - "traefik.http.routers.traefik.tls.domains[0].sans=*.caycehouse.com"
                    - "traefik.http.routers.traefik.tls=true"
                    - "traefik.http.routers.traefik.tls.certresolver=main"
                    - "traefik.http.routers.traefik.service=api@internal"
                    - "traefik.http.services.traefik.loadbalancer.server.port=8080"
                  placement:
                    constraints:
                      - node.role == manager
                      - node.hostname == {{ install_node }}
          - networks:
              traefik_public:
                external: true
                driver_opts:
                  com.docker.network.driver.mtu: 1280
