---
- name: Install headscale
  vars:
    service: headscale
  ansible.builtin.include_role:
    name: service

- name: Copy config.yaml to server
  ansible.builtin.copy:
    src: config.yaml
    dest: "{{ service_dir.path }}/etc-headscale"
    mode: "0644"
    owner: root
    group: root
  notify: Restart headscale
