---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./secret.sops.yaml
  - ./manifest.yaml

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: operator-oauth
      namespace: tailscale
    $patch: delete
