---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: atm10a
spec:
  components:
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: kopiur-repository
      namespace: kopiur-system
  interval: 1h
  path: ./kubernetes/apps/games/atm10a/app
  postBuild:
    substitute:
      APP: atm10a
      # renovate: datasource=custom.curseforge-modpack depName=all-the-mods-10-aeronautics
      MODPACK_VERSION: "0.5.1"
      KOPIUR_CAPACITY: 32Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: games
  wait: false
