---
- name: Install free-games-claimer
  vars:
    service: free-games-claimer
  ansible.builtin.include_role:
    name: service

- name: Set daily cron to run free-games-claimer.
  ansible.builtin.cron:
    name: "run free-games-claimer daily"
    minute: "0"
    hour: "17"
    job: "docker start fgc"
  become: false
