---
- name: Install on specific node
  vars:
    install_node: "houseco-3"
  block:
    - name: Create needed dir
      when: inventory_hostname == install_node
      ansible.builtin.file:
        path: /var/data/monica/{{ item }}
        recurse: true
      loop:
        - monica
        - database

    - name: Deploy Stacks
      when: inventory_hostname == play_hosts[0]
      community.docker.docker_stack:
        state: present
        name: monica
        compose:
          - services:
              monica:
                image: monica:4.0.0
                environment:
                  APP_ENV: production
                  APP_KEY: "{{ monica.app_key }}"
                  DB_HOST: tasks.db
                  DB_USERNAME: "{{ monica.mysql_user }}"
                  DB_PASSWORD: "{{ monica.mysql_password }}"
                volumes:
                  - /var/data/monica/monica:/var/www/html/storage
                networks:
                  - internal
                  - traefik_public
                deploy:
                  labels:
                    - "traefik.docker.network=traefik_public"
                    - "traefik.http.routers.monica.rule=Host(`monica.caycehouse.com`)"
                    - "traefik.http.routers.monica.entrypoints=https"
                    - "traefik.http.services.monica.loadbalancer.server.port=80"
                    - "traefik.enable=true"
                  placement:
                    constraints:
                      - node.hostname == {{ install_node }}
              db:
                image: mysql:5.7
                environment:
                  MYSQL_RANDOM_ROOT_PASSWORD: "true"
                  MYSQL_DATABASE: "{{ monica.mysql_database }}"
                  MYSQL_USER: "{{ monica.mysql_user }}"
                  MYSQL_PASSWORD: "{{ monica.mysql_password }}"
                volumes:
                  - /var/data/monica/database:/var/lib/mysql
                networks:
                  - internal
                deploy:
                  placement:
                    constraints:
                      - node.hostname == {{ install_node }}
          - networks:
              traefik_public:
                external: true
                driver_opts:
                  com.docker.network.driver.mtu: 1280
              internal:
                driver: overlay
                driver_opts:
                  com.docker.network.driver.mtu: 1280
                ipam:
                  config:
                    - subnet: 172.16.23.0/24
