---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/batch/cronjob_v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: zfs-scrub
spec:
  schedule: "0 3 * * 0"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: zfs-scrubber
              image: ghcr.io/heavybullets8/zfs-scrubber:1.1.2@sha256:d142396cbf0926b84a586666b777e357c622c7780bcf1444af4384bf3f14411b
              env:
                - name: ACTION
                  value: scrub
                - name: ZFS_POOL
                  value: tank
                - name: PUSHOVER_NOTIFICATION
                  value: "false"
                - name: TALOS_VERSION
                  # renovate: datasource=custom.talos-factory depName=siderolabs/talos
                  value: v1.13.5
              securityContext:
                privileged: true
              volumeMounts:
                - name: dev-zfs
                  mountPath: /dev/zfs
          volumes:
            - name: dev-zfs
              hostPath:
                path: /dev/zfs
