name: Deploy with Ansible

on:
  push:
    branches:
      - main
      
concurrency: ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - name: Tailscale
        uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.38.4
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@f2bfd4510d1d0e52fedcb894e622c178cb06227d
        with:
          playbook: site.yml
          requirements: requirements.yml
          vault_password: ${{secrets.VAULT_PASSWORD}}
