name: Deploy with Ansible

on:
  push:
    branches:
      - main

concurrency: ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Tailscale
        uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:server,tag:ssh
          version: 1.48.2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1 # v2.6.1
        with:
          playbook: site.yml
          requirements: requirements.yml
          vault_password: ${{secrets.VAULT_PASSWORD}}
